---
- name: Desinstall application
  hosts: group1

  tasks:
    - name: Remove application directory
      file:
        path: "{{ appdir }}"
        state: absent
    - name: Remove User
      user:
        name: "{{ appuser }}"
        state: absent
        force: true

- name: Desinstall DB
  hosts: group2
  tasks:

    # desinstall software + data (don't do that in prod!!!!!!)
    - name: Desinstall Postgresql server
      apt:
        name: 
          - postgresql-13
          - postgresql-common
        autoremove: true
        purge: true
        state: absent

