# Playbook deploying my super app with user appu 
# Version: 1.0
---
# Play 1
- name: Install application
  hosts: group1
  tags: app

  tasks:
    
    # Task 0
    - name: Debug variables
      debug:
        msg: 
          - "appuser: {{ appuser }}" 
          - "appdir: {{ appdir }}"

    # Task 1
    - name: Create User
      user:
        name: "{{ appuser }}"
        create_home: false
        home: "{{ appdir }}"
        shell: /usr/bin/bash
        system: true

    # Task 2
    - name: Create application directory
      file:
        path: "{{ appdir }}"
        state: directory
        owner: "{{ appuser }}"
        group: "{{ appuser }}"
        mode: 0750

    # Task 3
    - name: Debug 1
      debug:
        msg: "Task #3 of Play #1"

    - name: Copy app artifact
      copy:
        src: "{{ item }}"
        dest: "{{ appdir }}/"
        owner: "{{ appuser }}"
        group: "{{ appuser }}"
        mode: preserve
      with_items: "{{ files_to_copy }}"
      #with_items:
      #  - files/dummy.txt
      #  - files/dicton.txt
      #  - files/meteo.md

    - name: Copy app config
      template:
        src: dummyconfig.j2
        dest: "{{ appdir }}/dummyconfig.conf"
        owner: "{{ appuser }}"
        group: "{{ appuser }}"
        mode: preserve


# Play 2
- name: Dummy Play 2
  hosts: group1
  tags: vars
  tasks:

    - name: Debug var groups
      debug:
        var: groups['group2'][0]

    - name: Debug var ansible facts
      debug:
        msg: "{{ ansible_facts['os_family'] }}"

    - name: Debug hosts from group1
      debug:
        msg: "{{ item }}"
      with_items: "{{ groups['group1'] }}"

    - name: Debug items
      debug:
        msg: "{{ item }}"
      with_items:
        - dummy
        - coffee
        - sun
        - snow


# Play 3
- name: Install DB
  hosts: group2
  tags: db

  tasks:

    - name: Install Postgresql server apt
      tags: software
      apt:
        name: postgresql-13
        state: present
      when: ansible_facts['os_family'] == 'Debian'

    - name: Install Postgresql server yum
      tags: software
      yum:
        name: postgresql-13
        state: present
      when: ansible_facts['os_family'] in rhl_family # ['RedHat', 'CentOS']

    - name: Stop service
      systemd:
        name: postgresql
        state: stopped



